# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bagzz' do
  pod 'Alamofire', '~> 5.2'
  pod 'SWXMLHash', '~> 5.0.0'
  use_frameworks!

  # Pods for Bagzz

end
